export const GET_TODO_LOADING="GET_TODO_LOADING"
export const GET_TODO_SUCCESS="GET_TODO_SUCCESS"
export const GET_TODO_ERROR="GET_TODO_ERROR"


export const ADD_TODO_LOADING="ADD_TODO_LOADING"
export const ADD_TODO_SUCCESS="ADD_TODO_SUCCESS"
export const ADD_TODO_ERROR="ADD_TODO_ERROR"


export const LOGIN_LOADING="LOGIN_LOADING"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_ERROR="LOGIN_ERROR"

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"

